# Limited configuration instead of default_config
# https://www.home-assistant.io/integrations/default_config
automation:
bluetooth:
frontend:
history:
isal:
logbook:

homeassistant:
  name: HACS-Atmo
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.0.0.0/8
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant

logger:
  default: info
  logs:
    custom_components.atmo: debug
